### PR TITLE
ignore link check when user has not selected a custom theme

### PR DESCRIPTION
**Pull request by flyher**
Clicking Save will trigger an error when the user forgets to fill in the custom link and switches to another theme.

ignore theme link check

### CODE REVIEW

**Comment by salarcode** [comment]
The point of this check is when rule type is Auto, then the custom Urls will be used. This change will break.
Sorry this is by design even though it's not very obvious!

**Comment by flyher** [comment]
Since Auto Theme is selected, it shouldn't continue to check for user-defined settings.
It looks like the theme definition doesn't need so many parameters.

**Comment by salarcode** [comment]
There is no Auto theme, Auto means either Light or Dark themes will be used. That means settings for both of these themes needs to be correct and thus the validation happens.

Sorry but this PR can cause invalid URLs in themes

**Comment by flyher** [comment]
I understood your explanation, I was the one who misinterpreted the 'auto' here.

**Pull request closed without merging**
